[build]
  command = "npm run build:all"
  publish = "dist"
  functions = "netlify/functions"

# Special redirect for the intake form
[[redirects]]
  from = "/intake"
  to = "/admin/intake"
  status = 200

[[redirects]]
  from = "/intake/*"
  to = "/admin/intake/:splat"
  status = 200

# SPA fallback for admin dashboard
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# SPA fallback for student dashboard
[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200