[build]
  publish = "dist"
  command = "npm run build:netlify"

# Static assets rewriting
[[redirects]]
  from = "/admin/assets/*"
  to = "/admin/assets/:splat"
  status = 200

[[redirects]]
  from = "/student/images/*"
  to = "/student/images/:splat"
  status = 200

# Application routing
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/student"
  to = "/student/"
  status = 301
  
[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200

[[redirects]]
  from = "/intake"
  to = "/admin/index.html"
  status = 200
  
[[redirects]]
  from = "/intake/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200