[build]
  command = "npm run build:all"
  publish = "dist"
  functions = "netlify/functions"

# Direct routes with specific paths
[[redirects]]
  from = "/admin"
  to = "/admin/login"
  status = 302

[[redirects]]
  from = "/admin/login"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/student"
  to = "/student/index.html"
  status = 200

# Special redirect for the intake form
[[redirects]]
  from = "/intake"
  to = "/admin/intake"
  status = 200

[[redirects]]
  from = "/intake/*"
  to = "/admin/intake/:splat"
  status = 200

# Asset handling for images and other static files
[[redirects]]
  from = "/admin/assets/*"
  to = "/admin/assets/:splat"
  status = 200

[[redirects]]
  from = "/student/images/*"
  to = "/student/images/:splat"
  status = 200

# SPA fallbacks
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200

# Default fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200